name: Auto Blogger Post

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📥 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the auto-blogger script
        run: python Information-Blogger/main.py

      - name: Run Blogger Auto Poster
        run: python Information-Blogger/main.py
        env:
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
          BLOGGER_PASSWORD: ${{ secrets.BLOGGER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          
          